Particular/NServiceBus.AzureStorageQueues

src/Transport/Config/AzureQueueConfig.cs

Reverts Particular/NServiceBus.AzureStorageQueues#10

Revert "Issues 9 queue name override"

---

src/Transport/Config/AzureQueueConfig.cs

Issues 9 queue name override

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Tests/app.config
src/Tests/packages.config
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/packages.config

Azure SDK bump up to 6.2

---

src/Transport/AzureMessageQueueCreator.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/packages.config

Part of https://github.com/Particular/PlatformDevelopment/issues/610

Added coderules

---

src/Transport/AzureMessageQueueReceiver.cs
src/Transport/MessagePump.cs

Use core purge setting

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Sending/When_dispatch_fails.cs
src/Transport/Dispatcher.cs
src/Transport/MessagePump.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/UnableToDispatchException.cs

Logging dispatch failures

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs

To address various problems when changing configurations and obtaining values from the previous run.

Cleaning queues moved from the clean up to the test configuration

---

src/Transport/MessagePump.cs

Handling TransportTransactionMode.None

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/NamespaceSetup.cs

Connects to #60
solving it by clearing all the queues before every test

Clear all the queues before every test

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/packages.config

also remove inferred nuget dependencies

update to WindowsAzure.Storage 7

---

src/Transport/AzureMessageQueueCreator.cs

Setup queues for SendingAddresses

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/API/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/Config/QueueIndividualizer.cs
src/Transport/Config/SafeRoleEnvironment.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/CreateQueueClients.cs
src/Transport/Dispatcher.cs
src/Transport/EnvelopeDeserializationFailed.cs
src/Transport/ICreateQueueClients.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/Shortener.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/723
Going through public types and hiding them, for that purpose I signed ATT dll and also change dll name and default namespace name to match project name

Hiding public types

---

src/Transport/MessagePump.cs

Connects to #67 
@Particular/azure-storage-queues-maintainers please review

Removed outer catch of OperationCanceledException

---

src/Transport/AzureStorageQueueInfrastructure.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/723
This addresses my discussion with @SimonCropp to do not pass settings all around. I've simplified the class by creating the serializer eagerly.

Create serializer eagerly in the constructor

---

src/Transport/FodyWeavers.xml
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/packages.config

https://github.com/Fody/Janitor/issues/16
Ping @Particular/azure-storage-queues-maintainers :)

Update Fody.Janitor to resolve IDisposable[] issues

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/WellKnownConfigurationKeys.cs

* PurgeOnStartup
* DefaultQueuePerInstance
Connects to Particular/PlatformDevelopment#723

Removing deprecated configuration options:

---

src/Transport/MessagePump.cs

Connects to Particular/PlatformDevelopment#723
* moved success call right after successful receive, since there is no need to wait until the limiter has been passed and messages have been dispatched
* do no longer arm (.fail) the circuit breaker when message processing fails. This was basically useless since the it will always call success after polling the queue and therefore immediately disarm the CB again. If message handling fails this constantly logs "circuit breaker is now armed" but never actually triggering. According to @yvesgoeleven it's intended to not trigger on repeated message processing failures, so it seems like we can remove it there. The only reason the circuit breaker now triggers is in scenarios where ASQ can't be read over the configured time period. …

Changed circuitbreaker success and failure calls

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0001/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails.cs

Connects to: https://github.com/Particular/NServiceBus/pull/3676

[WIP] When_timeout_dispatch_fails test updated

---

src/Transport/AzureMessageQueueCreator.cs
src/Transport/AzureMessageQueueReceiver.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/723
This closes #97, closes #96

Minor fixes

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0003/Sagas/When_saga_id_changed.cs
src/AcceptanceTests/Configuration/Should_accept_no_mappings_at_all.cs
src/AcceptanceTests/NamespaceSetup.cs
src/AcceptanceTests/Sending/When_dispatching_fails.cs
src/AcceptanceTests/Sending/When_dispatching_to_other_account.cs
src/AcceptanceTests/Sending/When_message_is_sent_with_time_to_be_received_set_to_more_than_7_days.cs
src/Tests/App_Packages/ApiApprover.3.0.1/PublicApiApprover.cs
src/Tests/App_Packages/ApiApprover.3.0.1/PublicApiGenerator.cs

[SetUp] changed to [OneTimeSetup]
according to https://github.com/nunit/docs/wiki/SetUpFixture-Attribute

SetUpFixture fix up

---

src/Transport/MessagePump.cs

Related to https://github.com/Particular/NServiceBus/issues/3883

Avoiding allocations with Task.ContinueWith by opting-in for delegate caching

---

src/Transport/CreateQueueClients.cs

Related to https://github.com/Particular/NServiceBus/issues/3883

Avoid closure in CreateQueueClients

---

src/Transport/AzureMessageQueueReceiver.cs

instead of an enumerable to save allocations

QueueReceiver only allocates once for empty receives and returns a list

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Receiving/When_receiving_a_message.cs
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/MessagePump.cs
src/Transport/MessageRetrieved.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/ReceiveStrategy.cs

Pop receipt coherent handling

---

src/Tests/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/AzureStorageQueueTransport.cs

Related to https://github.com/Particular/NServiceBus/pull/3816

Added IMessageDrivenSubscriptionTransport marker to transport def

---

src/Transport/AzureMessageQueueReceiver.cs
src/Transport/MessagePump.cs
src/Transport/MessageRetrieved.cs

I was reviewing https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/143 and saw the following behavior change:
Unwrapping happens on the worker thread pool concurrently (deserialization is currently a CPU bound operation)
Unwrapping happens sequentially on the receive thread per message
When I moved the unwrapping into the receive I found out that it has significant perf boost when we can free up the receive thread. See https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/79 
This PR goes back to concurrent unwrapping and aligns cloud queue operations under the umbrella of the `MessageRetrieved ` class.

Unwrapping raw messages is done concurrently

---

GitVersion.yml
src/NServiceBus.AzureStorageQueues.sln.DotSettings
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/packages.config

Connects to Particular/V6Launch#3

Update to GitVersion 3.6.3

---

src/Tests/DelayDelivery/LockManagerTests.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/DelayDelivery/LockManager.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs
src/Transport/DelayDelivery/TableExtensions.cs
src/Transport/DelayDelivery/TimeoutEntity.cs
src/Transport/DelayDelivery/TimeoutsPoller.cs
src/Transport/Dispatcher.cs

fixes #179
also fixes nullreference exception in TimeoutEntity

better use of cancellationToken

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/app.config
src/AcceptanceTests/packages.config
src/NServiceBus.AzureStorageQueues.TransportTests/app.config
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Tests/app.config
src/Tests/packages.config
src/Transport/DelayDelivery/TimeoutEntity.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/app.config
src/Transport/packages.config

cache JsonSerializer in TimeoutEntity and add newtonsoft dependency

---

src/AcceptanceTests/Sending/When_delaying_messages_natively.cs
src/Tests/NServiceBus.Azure.Transports.WindowsAzureStorageQueues.approved.cs
src/Transport/Config/AzureStorageTransportExtensions.cs

This PR makes Native Timeouts internaliz till doco and migration arrives.

Internalize UseNativeTimeouts 

---

src/AcceptanceTests/Configuration/When_sending_to_another_account_wo_aliases.cs
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs

Fir for explicit send to queue@connectionstring with no aliases enabled

---

src/AcceptanceTests/Configuration/When_sending_to_another_account_wo_aliases.cs
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs

Hotfix 7.0.2 to develop

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/app.config
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Tests/app.config
src/Tests/packages.config
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/packages.config

JSON.NET dependency bump up

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec
src/Transport/DelayDelivery/SimpleJSON.cs
src/Transport/DelayDelivery/TimeoutEntity.cs

Connects to #221 
This PR replaces JSON.Net serialization of Timeouts' headers with SimpleJSON.

SimpleJSON for storying timeouts

---

src/Tests/NServiceBus.Azure.Transports.WindowsAzureStorageQueues.approved.cs
src/Transport/DefaultMessageEnvelopeUnwrapper.cs
src/Transport/Dispatcher.cs
src/Transport/MessageWrapper.cs

Simplifying TTBR handling

---

src/Transport/NServiceBus.AzureStorageQueues.csproj

Removal of unneeded JSON.NET reference in the project.

---

src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/BackoffStrategy.cs
src/Transport/MessagePump.cs

BackoffStrategy per receiving tasks

---

src/AcceptanceTests/Sending/When_dispatching_fails.cs
src/Directory.Build.props
src/Transport/Shortener.cs
src/TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs

Swapping crypto providers to .NET Standard equivalent

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

missing nuget for `dotnet test` execution required for .netcore

required package for runnign tests on .netcore

---

src/AcceptanceTests/Sending/When_dispatching_fails.cs

`When_dispatching_fails.Should_log_send_related_error` test is executed, it uses `WebRequest.DefaultWebProxy` to fail the 2nd test. This is working for Full .NET framework, but not for the .NET Core. For .NET Standard of the Storage library, it appears `WebRequest.DefaultWebProxy` is not used.
Test on .NET Core [fails](https://builds.particular.net/viewLog.html?buildId=232428&buildTypeId=NServiceBus_Transports_NServiceBusAzureStorageQueues_32TestsNetCoreOnWindows). Instead, this PR takes uses `OperationContext.GlobalSendingRequest` to throw an exception.
I've raised an issue with Storage [here](https://github.com/Azure/azure-storage-net/issues/534).

fixing a test on .netcore

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

Changes needed to run and report test results in Linux

Show test results in Linux

---

src/Transport/AzureStorageQueueInfrastructure.cs

Solves https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/236
Currently targeted at master. Needs to be re-targeted towards hotfix 
- `QueueAddressGenerator` is reused over send, receive and queue creation which introduces more potential for caching but a bit more contention on the concurrent dictionary
- `ToTransportAddress` passes the created queue name address generator.

Transport address

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/Transport/AzureStorageQueueInfrastructure.cs

Connects to #236
Ports #257 to release branch

ToTransportAddress

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/TestIndependence.cs
src/Transport/AzureStorageQueueInfrastructure.cs

Hotfix 7.4.2

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Directory.Build.props
src/NServiceBus.AzureStorageQueues.sln
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

This cleans up a few things related to moving to the new project system and Particular.Packaging.
It also adds SourceLink support.

Project cleanup

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj

fixes #293
Also includes a fody update as it was throwing null references on build

only enable delayed message poller if delayed delivery can be used

---

src/Transport/AzureStorageQueueInfrastructure.cs

hotfix-7.5.1

---

src/AcceptanceTests/Configuration/When_using_alias_instead_of_connection_string_for_default_account.cs
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs

Connects to #309
Replaces PR #310 
Fixes bug #308 - When using ASQ with default connection string and alias to secure it, messages sent with raw connection string instead of alias.

Hotfix-7.5.3

---

src/AcceptanceTests/Configuration/When_using_alias_instead_of_connection_string_for_default_account.cs
src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs

Connects to #312
Fixes bug #308 - When using ASQ with default connection string and alias to secure it, messages sent with raw connection string instead of alias.

Hotfix-7.4.3

---

src/AcceptanceTests/Configuration/When_using_alias_instead_of_connection_string_for_default_account.cs
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs

- `hotfix-7.5.3` needs to be merged into `release-8.0`.
- Resolving differences from between ASQ v7 and v8 testing that requires queue name sanitization
replaces #315

Forward porting hotfix-7.5.3 into release-8.0

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs

Replaces #317 
Closes #318 
also removes unnecessary settings access

Graceful shutdown for poller

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

Pending NServiceBus.Newtonsoft.Json

Prepare RTM

---

src/AcceptanceTests/CaptureSendingRequests.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively.cs
src/Tests/BackoffStrategyTests.cs
src/Transport/AzureStorageQueueInfrastructure.cs

Fixes #324 
This PR targets `develop`. Depending on what you want to do with it I might need to change the target branch as well as make it a hotfix

Delayed delivery polling fix

---

src/AcceptanceTests/Configuration/When_configuring_message_wrapper_serializer.cs
src/AcceptanceTests/Configuration/When_sending_messages_with_mapped_account_names.cs
src/AcceptanceTests/ConsoleLoggerFactory.cs
src/NServiceBus.AzureStorageQueues.sln.DotSettings
src/Transport/Config/DelayedDeliverySettings.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs
src/TransportTests/ConsoleLoggerFactory.cs

Update ReSharper .sln.dotsettings and fix inspections

Update ReSharper .sln.dotsettings

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

This updates development tooling on the `master` branch.
Note: This should not be squashed.

Master update dev tooling

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/NServiceBus.AzureStorageQueues.TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj

This updates development tooling on the `support-7.5` branch.
Note: It is okay for this to be squashed.

Update development tooling

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

This updates the approvals-related packages and also the newly released NUnit3TestAdapter.

Update approvals packages

---

src/Tests/MessagePumpHelpersTests.cs
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/MessagePump.cs
src/Transport/MessagePumpHelpers.cs
src/Transport/ReceiverConfiguration.cs

Hotfix 7.5.5

---

src/NServiceBus.AzureStorageQueues.TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs
src/NServiceBus.AzureStorageQueues.TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj
src/NServiceBus.AzureStorageQueues.TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj.DotSettings
src/NServiceBus.AzureStorageQueues.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.AzureStorageQueues.TransportTests/TransportTestLoggerFactory.cs
src/NServiceBus.AzureStorageQueues.TransportTests/When_on_error_throws.cs
src/NServiceBus.AzureStorageQueues.sln.DotSettings
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/MessagePump.cs
src/Transport/ReceiveStrategy.cs

Hotfix 7.5.7

---

src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/MessagePump.cs
src/Transport/ReceiveStrategy.cs
src/TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

Hotfix 8.1.4

---

GitVersion.yml
src/Transport/NServiceBus.AzureStorageQueues.csproj

Update Particular.Packaging in release-8.1

---

GitVersion.yml
src/Transport/NServiceBus.AzureStorageQueues.csproj

Update Particular.Packaging in master

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

For your review @mauroservienti

Update test projects to netcoreapp3.1 in master

---

src/AcceptanceTests/Configuration/When_configuring_account_names.cs
src/AcceptanceTests/Configuration/When_sending_message_with_custom_reply_to.cs
src/AcceptanceTests/Configuration/When_using_alias_instead_of_connection_string_for_default_account.cs
src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/Receiving/When_receiving_a_raw_json_message.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively_in_hybrid_mode.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively_with_send_only.cs
src/AcceptanceTests/Utils.cs
src/Tests/DelayDelivery/LockManagerTests.cs
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/AzureMessageQueueCreator.cs
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/BackoffStrategy.cs
src/Transport/DefaultMessageEnvelopeUnwrapper.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/Dispatcher.cs
src/Transport/MessagePump.cs
src/Transport/MessageRetrieved.cs
src/Transport/RepeatedFailuresOverTimeCircuitBreaker.cs
src/TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs

Closes #101 
Adds a bunch of log debug messages. I've tried to include message IDs wherever I can see that it makes sense.

Improve log levels

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

For your review @mauroservienti

Update test projects to netcoreapp3.1 in release-8.1

---

src/AcceptanceTests/CustomEndpointConfigurationExtensions.cs
src/AcceptanceTests/Receiving/When_MessageReceived_fails_to_unwrap_a_message.cs
src/AcceptanceTests/Receiving/When_receiving_a_message.cs
src/AcceptanceTests/Receiving/When_receiving_a_raw_json_message.cs
src/Transport/FodyWeavers.xml
src/Transport/MessageRetrieved.cs

Move poisonous messages to the error queue

---

src/Transport/DelayDelivery/DelayedMessagesPoller.cs

Concurrent dispatch in delayed message poller

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Sending/When_delaying_messages_and_delayed_delivery_is_disabled.cs
src/AcceptanceTests/TestSuiteConstraints.cs
src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/DelayedDeliverySettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs
src/Transport/Dispatcher.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/obsoletes-v9.cs
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

- Fix breaking changes related to removal of timeout manager
- Marked code related to non-durable messaging with TODO's
- Fix change related to AT persistence configuration

Breaking changes related to removal of timeout manager

---

src/Transport/AzureStorageQueueInfrastructure.cs

Adds diagnostics section for the transport, similar to https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/484
```json
"Azure Storage Queues transport": {
"ConnectionMechanism": {
"Queue": "QueueServiceClient",
"Table": "ConnectionString",
"Blob": "ConnectionString"
},
"DelayedDelivery": {
"NativeDelayedDeliveryIsEnabled": true,
"NativeDelayedDeliveryTableName": "delaysfa48ac287bebd2a9ae6e0029082fcc197eea8c90"
},
"TransactionMode": "ReceiveOnly",
"ReceiverBatchSize": "default",
"DegreeOfReceiveParallelism": "default",
"MaximumWaitTimeWhenIdle": "default",
"PeekInterval": "default",
"MessageInvisibleTime": "default"
}
```

Add diagnostics section

---

src/Tests/When_using_cosmos_db_connection_string.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/Config/BlobServiceClientProvidedByConnectionString.cs
src/Transport/Config/QueueServiceClientProvidedByConnectionString.cs
src/Transport/ConnectionStringValidator.cs

Backport of Connection string handling #492

Connection string handling

---

GitVersion.yml

Remove beta tag

---

src/Transport/NServiceBus.Transport.AzureStorageQueues.csproj

Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482

target framework update

---

src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/obsoletes-v10.cs

Requires https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/556

Obsolete APIs introduced in previous major for native pubsub

---

src/Transport/DelayDelivery/LockManager.cs

Create delayed delivery locks container w/o public access

---

src/AcceptanceTests/DelayedDelivery/When_error_in_delayed_delivery.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/Utils/ExceptionExtensions.cs
src/Transport/Utils/ExceptionHeaderHelper.cs

Fixes #648
- [Backported to version 10.0](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/651)
- [Backported to version 9.0](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/652)
- [Backported to version 8.2](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/653)

Delayed delivery missing exception headers

---

src/AcceptanceTests/DelayedDelivery/When_error_in_delayed_delivery.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/Utils/ExceptionExtensions.cs
src/Transport/Utils/ExceptionHeaderHelper.cs

Backport of https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/650 to version 10.0

Backport Delayed delivery missing exception headers to version 10.0

---

src/AcceptanceTests/DelayedDelivery/When_error_in_delayed_delivery.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/Utils/ExceptionExtensions.cs
src/Transport/Utils/ExceptionHeaderHelper.cs

Backport of https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/650

Backport delayed delivery missing exception headers to version 9.0

---

src/AcceptanceTests/DelayedDelivery/When_error_in_delayed_delivery.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/Transport/Utils/ExceptionExtensions.cs
src/Transport/Utils/ExceptionHeaderHelper.cs

Backport of https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/650

Backport delayed delivery missing exception headers to version to version 8.2

---

src/Transport/AzureStorageQueueInfrastructure.cs

Provide more guidance for missing config

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/DelayDelivery/DisabledNativeDelayDelivery.cs
src/Transport/DelayDelivery/INativeDelayDelivery.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs
src/Transport/Dispatcher.cs

To simplify the delayed delivery interface

The delay calculation moved to dispatcher

---

src/AcceptanceTests/Configuration/When_custom_clients_are_provided.cs
src/AcceptanceTests/Configuration/When_custom_queue_client_is_provided.cs
src/AcceptanceTests/Configuration/When_custom_queue_client_is_provided_without_connection_string.cs
src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/Tests/TestConfigurationScenarios.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/DelayDelivery/DisabledNativeDelayDelivery.cs
src/Transport/DelayDelivery/INativeDelayDelivery.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs
src/Transport/Dispatcher.cs

Backport of https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/664

Using UseQueueServiceClient instead of a connection string to configure the transport results in an exception when the endpoint starts

---

src/AcceptanceTests/NServiceBus.Transport.AzureStorageQueues.AcceptanceTests.csproj
src/TransportTests/NServiceBus.Transport.AzureStorageQueues.TransportTests.csproj

Part of https://github.com/Particular/DeveloperExperience/issues/1516

Update to core 7.6

---

src/AcceptanceTests/NServiceBus.Transport.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureStorageQueues.Tests.csproj
src/Transport/MessageReceiver.cs
src/Transport/NServiceBus.Transport.AzureStorageQueues.csproj
src/TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs
src/TransportTests/NServiceBus.Transport.AzureStorageQueues.TransportTests.csproj

Related to https://github.com/Particular/DeveloperExperience/issues/1516

Implement the ChangeConcurrency API

---

src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/Config/DelayedDeliverySettings.cs
src/Transport/obsoletes-v11.cs

Restored obsolete APIs `DisableTimeoutManager`  which are being removed

Obsolete APIs for next major

---

src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/Config/AzureStorageTransportExtensions.cs

Reintroduce hybrid mode

---

README.md

Updates the README to mention Azure Storage Explorer

Mention Azure Storage Explorer

---

src/AcceptanceTests/Receiving/When_receiving_large_message.cs
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/Dispatcher.cs
src/Transport/MessageRetrieved.cs
src/Transport/Utils/MessageWrapperHelper.cs

Fixes https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/991
I rebased my previous work that I did for a customer support request and figured I send in the PR

Make sure messages close to the size limit can be moved as is to the error queue

---

README.md
src/.gitignore
src/AcceptanceTests/Receiving/When_receiving_large_message.cs
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Dispatcher.cs
src/Transport/MessageRetrieved.cs
src/Transport/ReceiveStrategy.cs
src/Transport/Utils/MessageWrapperHelper.cs

This PR is a manual back port of the following commits that were made to master
- Add Azurite gitignore to src (#1016)
- Make sure messages close to the size limit can be moved as is to the error queue (#1002)
- Mention Azure Storage Explorer(#1014)

Backport msg size limit 10.0.5

---

src/AcceptanceTests/NServiceBus.Transport.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.Transport.AzureStorageQueues.Tests.csproj
src/TransportTests/NServiceBus.Transport.AzureStorageQueues.TransportTests.csproj

This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.

Upgrading to NUnit4 including all required dependencies

---

src/AcceptanceTests/DelayedDelivery/Native_message_delayed_retry.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/DefaultMessageEnvelopeUnwrapper.cs
src/Transport/UserProvidedEnvelopeUnwrapper.cs

handle wrapped native message on a delayed retry

---

src/AcceptanceTests/DelayedDelivery/Native_message_delayed_retry.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/DefaultMessageEnvelopeUnwrapper.cs
src/Transport/UserProvidedEnvelopeUnwrapper.cs

Fix for custom unwrapper not handling delayed retries - 12.0

---

src/AcceptanceTests/DelayedDelivery/Native_message_delayed_retry.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/DefaultMessageEnvelopeUnwrapper.cs
src/Transport/UserProvidedEnvelopeUnwrapper.cs

Fix for custom unwrapper not handling delayed retries - 13.0

---

src/Tests/RepeatedFailuresOverTimeCircuitBreakerTests.cs
src/Transport/FodyWeavers.xml
src/Transport/NServiceBus.Transport.AzureStorageQueues.csproj
src/Transport/RepeatedFailuresOverTimeCircuitBreaker.cs

Cherry-pick of https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1315

Fix race condition in RepeatedFailuresOverTimeCircuitBreaker

---

src/Transport/MessageReceiver.cs

Backport for https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1320
Backport of:
-  https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1320

Disposing circuit breaker when stopping the pump
