Particular/NServiceBus.AzureStorageQueues

src/Transport/Config/AzureQueueConfig.cs

Anyone who's using Azure Storage Queues transport and overriding `QueueName` of endpoint using `AzureQueueConfig`
Messages sent to destination endpoint(s) end up in the originating endpoint`s queue
```c#
class EndpointConfig : IConfigureThisEndpoint, AsA_Worker
{
public void Customize(BusConfiguration configuration)
{
configuration.UseTransport<AzureStorageQueueTransport>();
configuration.UsePersistence<InMemoryPersistence>();
}
class OverrideQueueNameForEndpoint : IProvideConfiguration<AzureStorageQueueTransport>
{
public AzureStorageQueueTransport GetConfiguration()
{
return new AzureStorageQueueTransport
{
QueueName = "kaboomriko"
};
}
}
class Boostrapper : IWantToRunWhenBusStartsAndStops
{
public IBus Bus { get; set; }
public void Start()
{
Bus.Send("particular.servicecontrol.dev", …
```

When QueueName is overriden using AzureQueueConfig, all messages will be sent to the originating endpoint instead of the specified destination

---

src/Transport/AzureMessageQueueCreator.cs

Only receiving queries should be created when asked for creation, sending queues will be created by receivers.

Only receiving queries should be created when asked for creation.

---

src/Transport/MessagePump.cs

Making sure that when stopping the endpoint no exception related to that is put into logs.
Fix #65

Stopping gracefully the endpoint

---

src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/MessageEnvelopeUnwrapper.cs
src/Transport/MessagePump.cs
src/Transport/MessageRetrieved.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj

Connects to #67
* MessagePump no longer uses Task.Run for async receive and no longer schedules a task for tokenSource.Dispose
* Ack of messages happens concurrently in the inner receive and only if there are slot on the semaphore available
* Unpacking the message envelop concurrently in the inner receive

MessagePump and Message Ack changes

---

src/Tests/API/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/AzureStorageTransportExtensions.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/MessagePump.cs

Connects to #67
* The factor that influences the receive speed the most is the pulling of messages from the queue.
* Introduced degree of parallelism (default `SquareRoot of MaxConcurrency but maximum 32`, let's call this dynamic degree of parallelism) which means that this version of the message pump will use by default a dynamic degree of parallel operations fetching messages from the queue defined by the default batch size. The concurrency settings of the core are not changed. It is perfectly valid to share the same semaphore which limits the number of messages.
* The maximum degree of parallelism is limited to a maximum of `32`. In my tests putting higher numbers hurts more than it helps.
* Switched the default batch size from `10 `to `32`. 
* Documentation PR: …

Message pump parallel

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/CreateQueueClients.cs
src/Transport/Dispatcher.cs

changing Dispatcher to execute sends concurrently instead of dispatching them sequentially. This results in batched sends being faster due to better usage of parallel http requests.
Tests showed that the `WhenAll` is can be up to 3x faster than the sequential code. Note that this heavily depends on the `ServicePointManager.DefaultConnectionLimit`. The sequential approach has the side-effect of easier request reuse compared to concurrent requests which have to open new connections when the connection limit is too high.
Also switched to using `ExistsAsync`. Async all the way.
I think there are valid reasons for both the previous approach (foreach-await) and the suggested code (WhenAll). The later should outperform the first when sending multiple messages from a handler. It's hard to name a …

Refactor Dispatcher to send messages concurrently

---

src/Transport/MessagePump.cs

Connects to #86 
The issue happens when v6 core (v7 transport) is the publisher and v5 core (v6 transport) is the subscriber: subscrber sends a message to publisher to register subscription needs.
In this context, message body is `null`, but v7 transport throws because it tries to push back to core a `MemoryStream` with `null` content
@Particular/azure-storage-queues-maintainers ping!

Ensure backward compatibility

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec
src/Transport/NServiceBus.AzureStorageQueues.csproj

Connects to Particular/PlatformDevelopment#723
Moving binaries 1 level up in a hierachy
The reason for that is to allign with others repositories where binaries is on the same level as src folder

Change location of binaries folder

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs
src/Transport/Config/QueueAddress.cs

The default account mapping was failing if logical-connection_string mapping was enabled. This fixes it.

Logical mapping of the default account fixed.

---

src/AcceptanceTests/Configuration/Should_accept_no_mappings_at_all.cs
src/AcceptanceTests/Configuration/When_mapping_account_names.cs
src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Utils.cs
src/Tests/API/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs
src/Transport/Config/Extensions/AzureStorageTransportAddressingExtensions.cs

After changing the API, passing the name for the default account is no longer required from the API point of view. Unfortunately it breaks UX when using one account as it requires to call the mapping method for no reason. This PR fixes this behavior allowing to skip the mapping when using only one account.
Tests have been provided.

An empty lambda is allowed for secure sends in one account

---

src/Transport/AzureStorageQueueTransport.cs

should fix https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/124
tested locally by removing `.SerializeMessageWrapperWith<JsonSerializer>();` from the transport config.
@Particular/azure-storage-queues-maintainers please review

Register message wrapper as system message

---

src/Transport/QueueAddressGenerator.cs

```ini
BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Xeon(R) CPU E5-2673 v3 2.40GHz, ProcessorCount=8
Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0
Type=ASQQeueNameGenerator  Mode=Throughput  
```
Method | Calls |        Median |        StdDev | Scaled |          Mean |    StdError |        StdDev |      Op/s |           Min |            Q1 |        Median |            Q3 |            Max |    Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
-------------------- |------ |-------------- |-------------- |------- |-------------- |------------ |-------------- |---------- |-------------- |-------------- |-------------- |-------------- |--------------- …

Queue address generator

---

src/AcceptanceTests/Configuration/Should_accept_no_mappings_at_all.cs
src/AcceptanceTests/Configuration/When_mapping_account_names.cs
src/AcceptanceTests/Sending/When_dispatching_to_other_account.cs
src/Tests/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/Extensions/AccountConfigurations.cs
src/Transport/Config/Extensions/AccountRoutingSettings.cs
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs
src/Transport/Config/Extensions/AzureStorageTransportAddressingExtensions.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj

Connects to https://github.com/Particular/PlatformDevelopment/issues/871
On the basis of https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/119
```
cfg.UseTransport<AzureStorageQueueTransport>()		
.UseAccountNamesInsteadOfConnectionStrings()
.DefaultAccountName(DefaultConnectionStringName)
.AccountRouting()
.AddAccount(AnotherConnectionStringName, anotherConnectionString);
```
The PR changes the place where an exception can be thrown when using `UseAccountNamesInsteadOfConnectionStrings`. Currently the method only marks up the configuration as one using account names. The application is done during call to `AzureStorageQueueInfrastructure.ConfigureReceiveInfrastructure`. This changes the place when the validation of providing the default account name occurs. That's the …

Align connection string mapping to ASB API

---

src/Transport/AzureMessageQueueReceiver.cs

Connects to #139 
This PR brings back resetting `timeToDelayNextPeek` to `0` only when any message is retrieved. See the comment added: https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/176826d7e2c59421a7c0ac6ffcde4513a3e34349#commitcomment-18570231

Delay retrieval when no messages properly

---

src/Transport/AzureMessageQueueReceiver.cs
src/Transport/MessagePump.cs
src/Transport/MessageRetrieved.cs

Addresses #142
Currently, when a malformed message is retrieved and cannot be deserialized properly ASQ handles it poorly. This PR addresses this need by explicitly catching any serialization related problems and putting a problematic message directly to the error queue.

Poison messages handling

---

src/Transport/Config/DefaultConfigurationValues.cs

`DefaultPeekInterval` was set at `50`. @danielmarbach calculations show that https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/139#issuecomment-238480885 this saturates the throughput of a single storage queue. This PR increase the value to the proposed one.

Change default values for receiver

---

src/Transport/AzureStorageQueueInfrastructure.cs

The `ToString` was meant to be a debugging helper. It incudes instance properties which you don't want to have in the default form in the transport address.

Made transport address translation explicit

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Receiving/When_receiving_a_raw_json_message.cs
src/Tests/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/AzureStorageTransportExtensions.cs
src/Transport/DefaultMessageEnvelopeUnwrapper.cs
src/Transport/Dispatcher.cs
src/Transport/IMessageEnvelopeUnwrapper.cs
src/Transport/MessageRetrieved.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/Transport/UserProvidedEnvelopeUnwrapper.cs

This PR adds a better extension point to support native integration scenarios where the unwrapper gets full access to the native cloud message.
If we merge this in we should add a native integration sample to docs similar to Sql and Rabbit.

Allow custom envelope unwrapping

---

src/AcceptanceTests/Receiving/When_receiving_a_raw_json_message.cs

Currently, #170 is failing because the merge commit contains `When_receiving_a_raw_json_message `with a message type that is not public.

Make When_receiving_a_raw_json_message message public for 6.1 preparation

---

GitVersion.yml

This amends `GitVersion.yaml` to mimic tag `6.2.1` on the `support-6.2` branch that did not include this tag resulting in wrongly versioned nuget.

Adding next-version attribute to GitVersion.yaml

---

packaging/nuget/nservicebus.azurestoragequeues.nuspec

Previous version of `nservicebus.azurestoragequeues.nuspec` had wrong references both to `NServiceBus.Core` and `WindowsAzure.Storage`. That resulted in problems both when installing the package in fresh project as well as doing nuget update.

nservicebus.azurestoragequeues.nuspec dependencies updated to correct versions

---

GitVersion.yml

Removing `next-version` attribute. This has been used to enforce proper version for nupkg without 6.2.2 tag on the repository.

Removing attribute enforcing next-version

---

src/AcceptanceTests/Configuration/When_receiving_from_another_account_wo_aliases.cs
src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Transport/Config/Extensions/AzureStorageAddressingSettings.cs

Because #193 required bumping up a lot of (beta) dependencies, porting it to `develop` causes a lot of conflicts. This PR provides an artificially created merge commit (`git commit-tree`) that merges back all the fixes.

Porting #193 to develop

---

src/Transport/AzureStorageQueueInfrastructure.cs

When `nativeTimeouts` are disabled, `Stop` threw an exception as the cancellation source. This PR fixes it.

Proper check for nullable cancellation token source

---

src/Transport/MessagePump.cs

Replaces the task tracking approach for shutdown with a simpler spinning over the semaphore (concurrency limiter). It still preserves the timing out after 30 seconds as well as the shutdown semantics.

Removed task tracking and replaced with spinning over concurrency limiter

---

GitVersion.yml

#219 removed the usage of GitVersion RC regex pattern. With GitVersion 4 the pattern has been changed and need to follow the following guidelines, see "Branch Configuration" on https://gitversion.readthedocs.io/en/latest/configuration/.
An example can be found 
See https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/GitVersion.yml

Bringing back the RC tagging for release branches

---

GitVersion.yml

This change moves `develop` back to 7.0. This will allow to ship Native Delayed Delivery in minor, reducing all the overhead connected with bumping up the major. After reviewing all the changes needed, I'd say that it's cost-wise to stay on minor for this one. Additionally, the rest of transports is also shipping as minor.

Moving develop back to 7.0

---

src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/BackoffStrategy.cs
src/Transport/MessagePump.cs

Fixes #241
Before the backup strategy was introduced the receiver used by the pump in parallel was designed to be stateless. By introducing the backup strategy in the constructor the receiver became stateful since the backup strategy has a field that needs to be updated. Before this change multiple parallel receive loops will try to update the same backup strategy and read/update the same field concurrently.
We decided against making the retriever per receive loop and just float in the backup strategy into the receiver to make it stateless again.

[WIP] Hotfix 7.4.1

---

src/AcceptanceTests/Sending/When_deferring_a_message_natively_and_delayed_delivery_is_disabled.cs
src/AcceptanceTests/Sending/When_delaying_messages_and_delayed_delivery_is_disabled.cs
src/Tests/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/AzureStorageTransportExtensions.cs
src/Transport/Config/DelayedDeliverySettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs

Connects to #250 
Fixes #250 
Prevent unnecessary Storage polling when an endpoint doesn't require features based on delayed delivery.

Allow delayed delivery polling to be disabled

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/TestIndependence.cs

This solves the issue of delayed messages with native delayed delivery not being stamped properly and then leaking over to other test runs.

Stamping all outgoing messages to also catch delayed delivery

---

src/Transport/Dispatcher.cs

Connects to #269 
Fixes to #269 
Related to https://github.com/Particular/NServiceBus.Persistence.AzureStorage/pull/167
Guard against bug in ASQ client library https://github.com/Azure/azure-storage-net/issues/540 by converting any sub-second TTBR to one second.

Guard against sub second ttbr

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs

Since the core beta is internally released that contains https://github.com/Particular/NServiceBus/pull/4956 we should re-enable those tests that were previously ignored

Re-enable ignored tests

---

src/Transport/AzureStorageQueueInfrastructure.cs

ToTransportAddress uses dash instead of dot for qualifier

---

src/AcceptanceTests/Sending/When_delaying_messages_natively_with_send_only.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/DelayDelivery/DelayedMessagesPoller.cs
src/TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs

Closes #287 
With the latest core beta changes, it is no longer possible to acquire the transport receive transaction mode for send-only endpoints. This PR switches to only acquire the tx mode for normal endpoints. Send-only endpoints behave in `isAtMostOnce = false` mode.

Fix native delay

---

src/AcceptanceTests/Configuration/When_configuring_account_names.cs
src/AcceptanceTests/Configuration/When_sending_message_with_custom_reply_to.cs
src/AcceptanceTests/Configuration/When_sending_messages_with_mapped_account_names.cs
src/AcceptanceTests/Configuration/When_sending_to_another_account_wo_aliases.cs
src/AcceptanceTests/Utils.cs

Connects to #276 
These tests were using a spoofed 2nd account. Now they use two separate accounts.
@danielmarbach the tests I didn't like are `When_sending_messages_with_mapped_account_names` and `When_sending_message_with_custom_reply_to`. IMO they are unnecessarily complex and mix multiple concerns. We don't have to refactor them right now, but probably should address it at some point. For example, I could probably refactor `When_sending_messages_with_mapped_account_names` to use an "audit spy" endpoint to remove the complexity of native dequing and JSON parsing. If it's worth it, I'll go ahead and make the change.

Refactoring tests with second namespace

---

src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively_in_hybrid_mode.cs
src/AcceptanceTests/Utils.cs
src/NServiceBus.AzureStorageQueues.TransportTests/ConfigureAzureStorageQueueTransportInfrastructure.cs
src/Tests/NServiceBus.Azure.Transports.WindowsAzureStorageQueues.approved.cs
src/Tests/Utils.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/Config/AzureStorageTransportExtensions.cs
src/Transport/Config/DelayedDeliverySettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs

Fixes #292 (alternative approach)
This PR takes into consideration the [hybrid mode](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/294#issuecomment-348385339), where TimeoutManager and native Delayed Delivery run side by side.
To implement this and be complient with v8, change to `DelayedDeliverySettings` had to be [SemVer non-complient](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/296/commits/1542425b399b64c10ec18138133a30ad990d2947) (inherites from `ExposeSettings` just like in v8). That's the reason why this is not a patch only, but also a minor - adding new API `.DisableDelayedDelivery()`.

Release 7.5.0

---

src/AcceptanceTests/Sending/When_delaying_messages_natively.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively_in_hybrid_mode.cs
src/AcceptanceTests/Sending/When_delaying_messages_natively_with_send_only.cs

ATTs have a base `SetUp` method that is used to configure naming conventions.
Local ATTs shouldn't not hide it. Rather, should use a separate `SetUp` method (`SetUpLocal`) to run at the test startup time.

Hidding ATTs SetUp method

---

src/Transport/AzureStorageQueueTransport.cs

Related to https://github.com/Particular/ServiceControl.TransportAdapter/issues/23
- Registering the MessageWrapper in the conventions as a system message is not necessary because MessageWrapper implements IMessage
- Registering the MessageWrapper in the message metadata registry is not necessary because the XmlSerializer caches types during runtime when necessary
@Scooletz  and I did some digging and it looks like those changes were introduced for the acceptance tests around the 7.0.0 RC timeframe. When the core v6.0.0 final was released the XmlSerializer was already implemented with runtime caching of types where necessary. 
Related issue https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/124
The related PR for the issue above …

Remove MessageWrapper from Conventions and MessageMetadataRegistry

---

src/Transport/AzureStorageQueueTransport.cs

Remove unnecessary settings to simplify transport adapter scenarios.
- Registering the MessageWrapper in the conventions as a system message is not necessary because MessageWrapper implements IMessage
- Registering the MessageWrapper in the message metadata registry is not necessary because the XmlSerializer caches types during runtime when necessary
For more information see https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/304

Hotfix 7.5.2

---

src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/TransportTests/When_modifying_incoming_headers.cs

Do not mutate original message headers between processing and recoverability

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Sending/When_message_is_sent_with_time_to_be_received_set_to_more_than_30_days.cs
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Transport/DelayDelivery/LockManager.cs
src/Transport/Dispatcher.cs
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

Fixes #325 
Supersedes #334 
* New Storage client 9.3.2
* Default message TTL set to 30 days (not using infinite)

Update Storage client and extend default TTL

---

src/AcceptanceTests/NServiceBus.AzureStorageQueues.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureStorageQueues.Tests.csproj
src/Transport/NServiceBus.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.AzureStorageQueues.TransportTests.csproj

This updates development tooling on the `support-8.0` branch.
Note: This should not be squashed.

Support 80 update dev tooling

---

.gitattributes

Remove `merge=union` from `.gitattribute` file to avoid auto-resolving conflicts by taking changes from both sides.

Remove merge=union git attribute

---

src/Transport/DelayDelivery/LockManager.cs

I was able to randomly reproduce the case when
```
exception.RequestInformation.ErrorCode == BlobErrorCodeStrings.LeaseIdMismatchWithLeaseOperation
```
was set. In all those cases `409` was also present. 
The stack trace we got from the customer
```
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (409) Conflict. (Failed to fetch delayed messages from the storage) ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](System.IAsyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions+<>c__DisplayClass4.<CreateCallbac …
```

Prevent conflict exception

---

src/Transport/AzureStorageQueueInfrastructure.cs

The following will be written to the diagnostics file:
```json
"Azure Storage Queues transport": {
"ConnectionMechanism": {
"Queue": "QueueServiceClient",
"Table": "ConnectionString",
"Blob": "ConnectionString"
},
"DelayedDelivery": {
"NativeDelayedDeliveryIsEnabled": true,
"NativeDelayedDeliveryTableName": "delaysfa48ac287bebd2a9ae6e0029082fcc197eea8c90",
"TimeoutManagerEnabled": false
},
"TransactionMode": "ReceiveOnly",
"ReceiverBatchSize": "default",
"DegreeOfReceiveParallelism": "default",
"MaximumWaitTimeWhenIdle": "default",
"PeekInterval": "default",
"MessageInvisibleTime": "default"
}
```

Add diagnostics section

---

src/Tests/When_ConnectionStringValidator_is_used_with_cosmosdb_connection_string.cs
src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/Config/BlobServiceClientProvidedByConnectionString.cs
src/Transport/Config/QueueServiceClientProvidedByConnectionString.cs
src/Transport/ConnectionStringValidator.cs

The connection string is becoming optional with the introduction of clients. Since it cannot be deprecated, we still need to support it yet throw when an attempt to use a Cosmos DB Table API connection string is used for either queue or blob client.

Connection string handling

---

src/Transport/RepeatedFailuresOverTimeCircuitBreaker.cs

Similar to https://github.com/Particular/NServiceBus.SqlServer/pull/840.
Less of a concern here since the delay is only 1 second, but I don't see a reason for not respecting the token. The only call is [here](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/3ec463e0a34f5d2959bea62d511a20c3f4b5f26a/src/Transport/MessageReceiver.cs#L166), which is a regular (exception throwing) method, so no changes are required there.

respect cancellation token in circuit breaker

---

.github/workflows/release.yml

This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.

Use Key Vault certificate for signing - release-10.0

---

.github/workflows/release.yml

This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.

Use Key Vault certificate for signing - release-9.0

---

.github/workflows/release.yml

This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.

Use Key Vault certificate for signing - release-8.2

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/DelayDelivery/DisabledNativeDelayDelivery.cs
src/Transport/DelayDelivery/INativeDelayDelivery.cs
src/Transport/DelayDelivery/NativeDelayDelivery.cs

Simplifies the delayed delivery code by extracting all of the disabled behavior into it's own class and only instantiating the original if it is needed. This allows us to avoid creating the blob service client unless it is needed.

Simplify delayed delivery

---

README.md
src/.gitignore
src/AcceptanceTests/Receiving/When_receiving_large_message.cs
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/Dispatcher.cs
src/Transport/MessageRetrieved.cs
src/Transport/Utils/MessageWrapperHelper.cs

Related to issue: #991 - Improve handling of messages that are close to the max body limit 
Backport of fix provided in #1002 to release 12.0
PR: #1002 - Make sure messages close to the size limit can be moved as is to the error queue
This also includes a couple of minor changes to documentation/gitignore:
PR: #1016 - Add Azurite gitignore to src
PR: #1014 - Mention Azure Storage Explorer

Improve handling of messages that are close to the max body limit

---

README.md
src/.gitignore
src/AcceptanceTests/Receiving/When_receiving_large_message.cs
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/AzureMessageQueueReceiver.cs
src/Transport/AzureStorageQueueTransport.cs
src/Transport/Dispatcher.cs
src/Transport/MessageRetrieved.cs
src/Transport/Utils/MessageWrapperHelper.cs

This PR is a manual back port of the following commits that were made to master
- Add Azurite gitignore to src (#1016)
- Make sure messages close to the size limit can be moved as is to the error queue (#1002)
- Mention Azure Storage Explorer (#1014)

Backport msg size limit 11.0.1

---

src/TransportTests/NServiceBus.Transport.AzureStorageQueues.TransportTests.csproj

This PR includes a fix for the build warnings from the compile items referencing the generated package path property.

Fix build warning

---

src/AcceptanceTests/NServiceBus.Transport.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Receiving/When_message_visibility_expired.cs
src/Tests/AtLeastOnceReceiveStrategyTests.cs
src/Tests/FakeQueueClient.cs
src/Tests/NServiceBus.Transport.AzureStorageQueues.Tests.csproj
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/MessageReceiver.cs
src/Transport/MessageRetrieved.cs
src/Transport/NServiceBus.Transport.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.Transport.AzureStorageQueues.TransportTests.csproj

This PR follows through on related changes done in [Amazon SQS](https://github.com/Particular/NServiceBus.AmazonSQS/pull/1861) but adjusts the core pieces of the change to Azure Storage Queue-specific behavior. Additionally, it brings in a number of layered tests that verify the code works as expected and doesn't accidentally break later.
And LRU cache to track the delivery attempts is not necessary because the receive count is automatically updated by the storage queue infrastructure.
The logic in `AtLeastOnceReceiveStrategy` has been updated significantly:
- Caching Acknowledged Messages: A cache (using `BitFaster.Caching.Lru`) is introduced to keep track of messages that have been marked as successfully completed. This helps in avoiding unnecessary retries for messages that are already …

Track messages that successfully completed the message or error pipeline but failed to get acknowledged due to expired leases

---

src/AcceptanceTests/NServiceBus.Transport.AzureStorageQueues.AcceptanceTests.csproj
src/AcceptanceTests/Receiving/When_message_visibility_expired.cs
src/Tests/AtLeastOnceReceiveStrategyTests.cs
src/Tests/FakeQueueClient.cs
src/Tests/NServiceBus.Transport.AzureStorageQueues.Tests.csproj
src/Transport/AtLeastOnceReceiveStrategy.cs
src/Transport/AtMostOnceReceiveStrategy.cs
src/Transport/MessageReceiver.cs
src/Transport/MessageRetrieved.cs
src/Transport/NServiceBus.Transport.AzureStorageQueues.csproj
src/TransportTests/NServiceBus.Transport.AzureStorageQueues.TransportTests.csproj

Backport of #1212 to `release-12`

Endpoint shuts down and triggers critical error while acknowledging   a message that has failed and exceeded the visibility timeout

---

src/Transport/AzureStorageQueueInfrastructure.cs
src/Transport/MessageReceiver.cs

This aligns the transport to stop the pumps on transport shutdown and at the same time makes sure the pumps stop method can be called multiple times. 
This is part of addressing some low-hanging fruit to align all transports for the transport seam usage scenarios to make sure pumps are stopped when the transport shuts down. 
I have tried to write a transport test for it to enforce it eventually for all transport but couldn't find a way to do that without introducing flags on the transport interface and using fancy techniques like default members which seams overkill

Stop pumps on shutdown

---

src/Tests/RepeatedFailuresOverTimeCircuitBreakerTests.cs
src/Transport/FodyWeavers.xml
src/Transport/NServiceBus.Transport.AzureStorageQueues.csproj
src/Transport/RepeatedFailuresOverTimeCircuitBreaker.cs

A port of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1066
> Serializing the arm/disarm actions is not enough. The state transition preceding the arm/disarm action must be captured in the lock as well, otherwise the state transitions could happen properly but then the arm/disarm actions could be executed by the processor in the wrong order, leaving the logic of the circuit breaker itself intact but the consequences of the arm/disarm actions in an incorrect state.
> 
> I also added xdoc as a way to document that the arm/disarm actions are called within a lock, and to maybe pave the way for this to be used as a shared component.

Fix race condition in RepeatedFailuresOverTimeCircuitBreaker
